server:
  port: 2008

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:2008/eureka/

spring:
  application:
    name: eurka-servey